language: node_js
    
node_js:
- "8"
- "10"
- "12"
- "node"

services:
- mongodb

before_script:
- node $TRAVIS_BUILD_DIR/loadData.js
- npm install -g gulp-cli

script:
- gulp lint
- npm test

sudo: false

deploy:
  provider: heroku
  app: openerz
  on:
    tags: true
    all_branches: true
  api_key:
    secure: KyHOcVLsv6/Ri/se3HG8jfJPRt8D1ypKC4jeEccI55ibpN/1nvZNxCbhJiMPAp34MwQ8k/Fu4EYXMW9epv3N4dAxTn04uOGWrIKx1eQGlZaBz1Jyi3M5/2KdBOmtL9YLMJ+gS7/e2COGHKXlunkPsCm7cXFTRbVYXEDlaGSopnI=
