openerz:
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
        - ${NODE_PORT}:8080
    links:
        - mongodb:mongodbhost
mongodb:
    build: images/mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --bind_ip_all --smallfiles --logpath=/dev/null # --quiet
