remote_theme: gustavoquinalha/jekyll-help-center-theme
title: "OpenERZ Hilfe"
email: odi@metaodi.ch
description: "Hilfe zur Benutung von OpenERZ."
baseurl: "/jekyll-help-center-theme"
url: "http://metaodi.ch/openerz/"
twitter_username: "odi"
github_username:  "metaodi"
color_theme:  "#0081ff"
color_text:  "#fff"
language:  "de"

# Build settings
markdown: kramdown
permalink: /:title/
